### ISSUE TITLE
Add a Setting to change 4 Personal Identification Number (PIN) of Ledger Nano S

### ISSUE THREAD

**Issue by ivorpad** [LedgerHQ/ledger-nano-s#1]
As requested via email:

Please add a Setting in the device to change the PIN. I think that — from a security point of view — changing PIN regularly is a good security practice (even banks prompt you to change PIN of debit cards), even more important in a device where the PIN can be seen in the screen, and wiping the device every time to change it is inconvenient and dangerous.

So my idea is:  Change PIN and verify with 2 random words from seed.

**Comment by btchip** [comment]
This will be included as one of the experiments with the SDK, available shortly - you'll be able to change the PIN in the settings menu, and need to enter the old one to do that (which is better than revealing words from the seed, security wise)

**Comment by jonathancross** [comment]
Is this complete now?  Listed as "Done" on the Roadmap: https://trello.com/c/8I01AJjU

**Comment by btchip** [comment]
Yes

**Comment by jonathancross** [comment]
Thanks!
