### ISSUE TITLE
random start for pin entry

### ISSUE THREAD

**Issue by ulrichard** [LedgerHQ/ledger-nano-s#12]
As each digit starts at 5, everybody within hearing range has 2^4 guesses to get your pin. That includes everybody with access to any microphone in your vicinity. All he has to do is count the key presses. On my devices the two buttons sound differently, and a simultaneous press is even easier to distinguish.
If it started out with a random number rather than 5555, that would increase the security. 
Of course it should be an option, as some people might not like it. Especially visually the impaired.

**Comment by Morveus** [comment]
This option is already available as a setting wit the most recent firmware :)

**Comment by jonathancross** [comment]
@btchip Fixed per #3

**Comment by lazaridiscom** [comment]
@gre , @btchip , it looks that this issue can be closed.
