### ISSUE TITLE
Security Issue: Ledger does not check operation mode and signs transaction for any coin in any mode

### ISSUE THREAD

**Issue by yura-pakhuchiy** [LedgerHQ/ledger-nano-s#13]
Nano Ledger S displays incorrect destination address when bitcoin wallet used in test-net mode. It displays main-net style adress (1...), instead of test-net one (m...). Everything else seems to work fine: amount and fee displayed correctly and transaction get signed. However, displaying main-net address may scare user away if he stores both main-net and test-net coins in the wallet.

**Comment by btchip** [comment]
Yes, there are two ways to fix that : either build the BTC app (https://github.com/ledgerhq/blue-app-btc) with COIN=bitcoin_testnet or invoke SET ALTERNATE COIN VERSION (https://github.com/LedgerHQ/blue-app-btc/blob/master/src/btchip_apdu_set_alternate_coin_version.c) in your code to set the new values (APDU would be E014000005006F00C401 for Testnet)

**Comment by yura-pakhuchiy** [comment]
@btchip Thank you for your reply!

Actually, it not my code. I have been testing Electrum and Mycelium wallets in test-net mode. I will report this issue to them and send link to your reply.

However, I think that it is a big security issue, that Ledger allows to sign transaction for any coin in any mode. I have made more tests, and was able to send bitcoin while Ledger was in DASH mode. Hardware wallets promise that you can use them even on infected computer and your coins will be safe. But this issue kills this promise. Consider following scenarios:

1. Buggy multi-currency wallet. You request to send 10 DASH, but wallet for some reason creates transaction which sends 10 BTC to BTC address with same derivation path as DASH you requested. In this case Ledger will ask you to confirm to send 10 DASH to correct address, but will sign transaction which sends 10 BTC.

2. Malicious shop. You come to the shop and want to pay with your Ledger there. They offer you to connect Ledger to their wallet to make payment. You agree, because it should be safe, since it is hardware wallet and you confirm transaction on device yourself. Then they generate DASH and BTC addresses with same derivation path from the same BIP39 seed, Ledger in DASH mode shows you DASH address, you confirm, but they sign BTC transaction for the same amount and broadcast it. They will be able to spend BTC since they have private key for both addresses (BTC and DASH).

Ledger should check in which mode it running and sign transaction only for corresponding network. I hope you can fix this issue in the next firmware update.

**Comment by btchip** [comment]
Thanks for the report - such control can be added easily in the application (no need to wait for a firmware update). I'll think a bit about it to support it in a way that doesn't make BIP 44 mandatory.

**Comment by yura-pakhuchiy** [comment]
@btchip Great! Let me know when application updates will be available. Thank you!

**Comment by yura-pakhuchiy** [comment]
@btchip Regarding BIP 44, one solution could be to add (on by default) option to enforce BIP44. Allow user to disable it, if he wants to use non standard derivation paths (after showing security warning). Or even better, allow user to add custom derivations paths (per coin) without disabling BIP44 checks completely.

**Comment by btchip** [comment]
The way I plan to do it is to check BIP 44 coin type when it's used (through an API accepting a signed blob linking the coin type to the other former SET ALTERNATE COIN VERSION parameters, which will be removed). Non BIP 44 derivation will still be allowed without security prompts, otherwise it'd get too confusing for many third party services (mostly those using a different scheme for multisignature services)

This doesn't prevent malicious services from accepting deposits for coin A on a non BIP 44 path then spend them for supposedly-coin-B on the same non BIP 44 path, but at that point it looks so obviously malicious that the community should blacklist them quickly.

**Comment by yura-pakhuchiy** [comment]
@btchip Few more thoughts regarding this issue:

1. It would be great to protect public keys for BIP44 derivations as well. Applications able to get BTC public keys (so they can check balances) without any confirmations when ledger is connected in altcoin mode.

2. BIP49 derivations should be protected as well (SegWit addresses).

3. Similar problem exists for ETH, ETC, ETH tesnets, RSK testnet. There is no way to tell which one coin is used. Ledger displays just ETH for all of them. This is a serious issue, because market price for ETH and ETC is 20 fold difference now. Displaying from address will solve the issue for Ethereum (as long as user uses different addresses for each network).

4. There should be option to display derivation path for advanced users. Otherwise how do you expect community would  blacklist malicious services quickly?

5. Alternatively way of protecting keys: Generate different keys for every altcoin by specifying altcoin name as seed password phrase. If users specifies his own password phrase, then add both strings. Eg., LTC seed password phrase "apple" would become "LTCapple". Document this behaviour and prompt user which method he want to use during seed restoration (this one as more secure, or original for users who already transfered coins to seed generated with original method).

6. Could you describe how SSH and PGP keys derived form BIP39 seed? Is there any chance that they can reveal any information about coin keys?

**Comment by jonathancross** [comment]
@btchip Any updates here?  There are some good questions from @yura-pakhuchiy which are unanswered since June. :/

**Comment by btchip** [comment]
We're redesigning many things around the locking mechanism and the way the client application interacts with the device. Should be available around Q1 2018.

**Comment by yura-pakhuchiy** [comment]
Almost 2 years passed. The issue is still reproducible with BTC app 1.3.2 (the last shown by ledger live as of today)...

**Comment by yura-pakhuchiy** [comment]
After 3 years Ledger seems finally fixed the issue after @monokh made more noise about it:
https://monokh.com/posts/ledger-app-isolation-bypass
https://www.ledger.com/updating-the-bitcoin-app-to-enhance-security
