### ISSUE TITLE
[Feature Request] Pivx Support

### ISSUE THREAD

**Issue by vzool** [LedgerHQ/ledger-nano-s#16]
Hi,

Do you have any plans to support PIVX?

Thanks

**Comment by h-alasadi** [comment]
Hello,

Can you please update us on your plans for PIVX?

Thanks

**Comment by btchip** [comment]
Sorry, Github notifications are not working, as usual. We have no plans to support PIVX so far - developers are free to get to it and get support on our developer slack at http://slack.ledger.co
