### ISSUE TITLE
FIDO U2F not working

### ISSUE THREAD

**Issue by slothbag** [LedgerHQ/ledger-nano-s#2]
I just tried to add the ledger nano S as a security token to Github and github says 'Signature Attestation Error' or something to those words.

I also tried it with other U2F devices like Trezor and it worked no problem.

**Comment by btchip** [comment]
We caught a late bug causing this issue with some U2F hosts, unfortunately after the release. A fix will be issued in the next update, in the meantime if you want to test the beta developer release feel free to send a mail to support@ledgerwallet.com and ask for it.

**Comment by throughnothing** [comment]
Having this same issue, has an update been released yet?  Where/How will I go to check for firmware updates for my Ledger?

**Comment by btchip** [comment]
Yes, firmware update 1.2 solves this issue - the update process is documented here : http://support.ledgerwallet.com/knowledge_base/topics/firmware-upgrade-and-application-manager. We advertise those updates on our Twitter account https://twitter.com/LedgerHQ and the next version of the application manager will also notify updates.
