### ISSUE TITLE
Randomize first characters of PIN

### ISSUE THREAD

**Issue by Transisto** [LedgerHQ/ledger-nano-s#3]
Size of numbers on the screen : 0.2 cm,
Knuckle movement when pressing the buttons : 1 cm or more

In the meanwhile I suggest holding the button to change the numbers in public places.

**Comment by btchip** [comment]
Thanks, we've also included another workaround in our roadmap : https://trello.com/c/wKEX5L4O/21-shuffle-pin-option

**Comment by btchip** [comment]
Done, optional in firmware 1.2
