### ISSUE TITLE
Different colors

### ISSUE THREAD

**Issue by yura-pakhuchiy** [LedgerHQ/ledger-nano-s#31]
I would like to buy second nano s for testing / development. There is no option to buy different color for nano s to avoid confusion and accidental use of primary device instead of test one. I can put sticker or something on device, but having it in different color is better solution.

**Comment by juan-cortes** [comment]
You can invert the display so that one is blue on black and the other is black on blue on the settings of the device.

**Comment by yura-pakhuchiy** [comment]
@juan-cortes this is a great idea, thank you!

However having hardware in different colors still would be great. To distinguish between switched off devices.

**Comment by danuker** [comment]
I would love a transparent version, to be able to inspect the PCB without voiding the warranty.

**Comment by juan-cortes** [comment]
@danuker you are in luck then, the nano s has a [transparent version](https://www.ledger.com/products/ledger-nano-s/transparent) and different colors too to fit what @yura-pakhuchiy wanted.
![image](https://user-images.githubusercontent.com/4631227/52532986-5dae6800-2d2d-11e9-8a88-49b77539b332.png)
