### ISSUE TITLE
Nano S displaying change address + change amount instead of receiving address with Mycelium and Electrum

### ISSUE THREAD

**Issue by Transisto** [LedgerHQ/ledger-nano-s#5]
https://github.com/spesmilo/electrum/issues/1961#event-817265722

**Comment by Transisto** [comment]
This bring me to ask, How is the change address verified ?

What if the change address (not displayed) is not one belonging to the Ledger wallet ?
Like what just happened...

**Comment by btchip** [comment]
That bug was caused by an unfortunate bug in the HW.1 code conversion process. It is fixed in the new BTC application provided with firmware 1.2 (closing commit is https://github.com/LedgerHQ/blue-app-btc/commit/ba6f5a785dbff7fd5e16cfe72597948fe51a35c4)
