### ISSUE TITLE
On boarding confirmation fails if wallet words contain duplicate words

### ISSUE THREAD

**Issue by slavox** [LedgerHQ/ledger-nano-s#6]
During a setup where the generated words contains a duplicate word:
The confirmation phase will ask you to retry if you are asked to verify one of the duplicate words and you select the wrong copy of the duplicate word in the list.

**Comment by btchip** [comment]
that's an interesting problem. Thanks, we'll look into it.

**Comment by jonathancross** [comment]
@btchip Any updates?

**Comment by btchip** [comment]
Fixed a long time ago in 1.3.1

**Comment by jonathancross** [comment]
Thanks!
