### ISSUE TITLE
Fido U2F doesn't seem to work with gmail/GitHub since 1.2 update

### ISSUE THREAD

**Issue by jlegoupil** [LedgerHQ/ledger-nano-s#7]
I updated to new firmware 1.2 and downloaded the Fido U2F app from the Ledger Manager (Chrome app).

When I try to login with the Fido U2F in gmail using Chrome (with OS X):
1) the device displays the "Confirm registration" screen
2) The device displays "Service 4141...4141" instead of "Service google.com"
3) if I press the left button (cancel), it doesn't cancel and returns the the "Confirm registration" screen
4) if I press the right button (OK), gmail answers "the key you are using is not registered for this account"

Note : I have a duress PIN setup on my device but I use my old PIN when powering the device

**Comment by jlegoupil** [comment]
~~Additionally, if I now try to register a new Fido U2F key with for example GitHub, GitHub displays the message "waiting for device" while the nano S displays "ready to authenticate" with no other options but to quit the app.~~

Edit: I withdraw this comment, key registration works on github (was using FF)

**Comment by jlegoupil** [comment]
I tried to log on gmail using the same previous configuration except this time on a Win7 machine and have the same symptomes.

**Comment by btchip** [comment]
If you upgraded from version 1.0, you need to register new U2F keys as the derivation format changed as an unfortunate side effect between 1.0 and 1.1

**Comment by jonathancross** [comment]
@jlegoupil  Seems this can be closed?

**Comment by jlegoupil** [comment]
Yes it certainly can.
