### ISSUE TITLE
Firmware update is not comprehensible and look very buggy.

### ISSUE THREAD

**Issue by Transisto** [LedgerHQ/ledger-nano-s#8]
Sorry for this mess, I rather post a half assed bug report and format it later than risk not following through onto something that I think is urgent.

I've seen too many error messages , unexpected and incomprehensible behavior trying to do the firmware update.

---

I've tried updating a Nano-S, I saw something on the screen asking to approve the update. I don't remember exactly but when I tried the update a 2nd time the ledger got forever stuck at "UPDATE" on the screen wherever I would plug it. (Looked Bricked)

![image](https://cloud.githubusercontent.com/assets/388716/19589729/f3a11202-973b-11e6-899d-e7578095314a.png)

I later found out that I had to click firmware on the other tab...

I tried updating another Ledger using another computer and different problem.
[ledger-manager-logs-1477033204318.txt](https://github.com/LedgerHQ/ledger-nano-s/files/543726/ledger-manager-logs-1477033204318.txt)

Every time I click "firmware" it update the firmware - (it seems like it did - no progress - no completion message)

Your button should say UPDATE FIRMWARE and UPDATE OSU then pop-up the disclaimer/warning about deletion of the seed requiring to agree.
![image](https://cloud.githubusercontent.com/assets/388716/19590264/eedf71b6-973e-11e6-87f2-2d0faf73030c.png)
Compared to Trezor Ledger notice is very easy to miss : 
![image](https://cloud.githubusercontent.com/assets/388716/19612884/30fc0b18-97b7-11e6-8502-26ecce114237.png)

Is it normal that the wallet say there is no update ?
![image](https://cloud.githubusercontent.com/assets/388716/19589330/aa44b3ea-9739-11e6-8c52-850da41a4da9.png)

I click : 
![image](https://cloud.githubusercontent.com/assets/388716/19590246/d2837d46-973e-11e6-95e2-900f1b217998.png)

I get : 
![image](https://cloud.githubusercontent.com/assets/388716/19590251/d9f99e48-973e-11e6-9049-d4d7d981b22a.png)

Ledger does not verify that the OSU is already updated or not. It's not clear whether it ever worked or not.

Ledger Manager addon taking 100% CPU
![image](https://cloud.githubusercontent.com/assets/388716/19590489/3638fa0e-9740-11e6-8f2e-1c7de1f99b16.png)

On two browser at once without a ledger connected:
![image](https://cloud.githubusercontent.com/assets/388716/19590516/5d1f2210-9740-11e6-855e-649aaa90a0e3.png)

CPU when killing one addon then killing the 2nd :
![image](https://cloud.githubusercontent.com/assets/388716/19590542/7df219de-9740-11e6-964e-94d3f6aefc01.png)

**Comment by Morveus** [comment]
It seems that you applied the OSU (which prepares the device for a firmware update) but not the firmware itself.

"Update" means that you now have to install the firmware, see the "Firmware" section in the Ledger Manager: there is an "OSU" button and a "Firmware" button. Plug the Nano S, wait for the "Update" screen to show, and click "Firmware".

**Comment by EricLarch** [comment]
Did you click on firmware (right button) after having clicked on osu? When
in update mode the Nano S is waiting for the firmware to be flashed

**Comment by jonathancross** [comment]
Any updates here?
Is there still issues to address with firmware updates given that it has been a year?

**Comment by btchip** [comment]
No, it works well for all purposes
